title: Code, art, and adventure.
author: rmwtaylor22
email: rmwtaylor22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about computer science, art, and stories from my experience as a young professional in the field.
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
