title: Rose White's blog
author: rmwtaylor22
email: rmwtaylor22@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about computer science creativity and soft skills
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  rmwtaylor22

show_excerpts: true # set to false to remove excerpts on the homepage
